# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x_position', models.BigIntegerField()),
                ('y_position', models.BigIntegerField()),
                ('level', models.PositiveSmallIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('last_accessed', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('last_accessed',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='game_session',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='unity_userdata.Player'),
        ),
    ]
